### PR TITLE
solved the Gitea support #2904 issue

### PR DESCRIPTION
**Pull request by Lemmynjash**
**Summary:**
/claim #2904

@algora-pbc /claim #2904

**Issue Reference(s):**
Feature request for [gitea](https://about.gitea.com/) Pull Requests support.

**Detailed summary on how i solved the issue**
I have solved the issue. Please see the attached GIF showing the before and after states, as well as the solution after successfully resolving the issue. Additionally, I have changed the wording on the 'show toast' popup to provide guidance on the solution.

Before 
Before error

After
Success!!

### CODE REVIEW

**Comment by Lemmynjash** [comment]
Hi @ngalaiko and @schacon  kidnly take a look and tip me I will appreciate ;)

**Comment by zcesur** [comment]
Hi @Lemmynjash - Algora cofounder here, thanks for attempting this bounty

From your GIFs I'm getting the sense that you're pushing to a GitHub repository, which is not what this issue is about. Have you reproduced the issue with a Gitea repository?

Until confirming that your code works with a Gitea repository, I recommend marking your PR as draft and removing your @mentions to the maintainers. Maintainers are often super busy and they appreciate receiving complete solutions or clear progress

This is the best way to be successful on Algora and we want you to be successful! Cheers

**Comment by Lemmynjash** [comment]
@zcesur Thank you for providing me with more insights. I appreciate your guidance. I will mark the PR as a draft and refrain from mentioning the maintainers until I've confirmed that my code works with a Gitea repository.

**Comment by Byron** [comment]
Thanks for contributing!

Since the PR wasn't active for over a month, and is now in a conflicting state, would you mind keeping it in your own fork until you have time to finalize it?

The plan is to do GitLab integration first and depending on how this is done, Gitea integration will probably be easier to integrate afterwards as well.

Thanks again.

**Comment by Qix-** [comment]
Going to close for now as I don't think this is going to be accept as-is. Thank you!

**Pull request closed without merging**
