### PR TITLE
Organize components by feature

### PR DESCRIPTION
**Pull request by mtsgrd**
I've been on a train for the last 3h, thought I could take a stab at moving some files around. Let me know what you guys think? *edit: had to stop halfway through, approaching my end station.

### CODE REVIEW

**Comment by Caleb-T-Owens** [comment]
Looks great!

**Comment by mtsgrd** [comment]
Cool cool, perhaps we can land as a partial step if it's going in the right direction?

**Comment by Caleb-T-Owens** [comment]
@mtsgrd I've got a PR that I'd like to merge first but after that, I'm happy to merge as a first step

**Comment by ndom91** [comment]
Yup, no other comments or hold-ups from me. Feel free to merge as first step whenever yuo're ready @Caleb-T-Owens.

Just noticed theres a bunch of merge conflicts now. Are you still waiting to merge your PR Caleb or has it already been merged? If its already been merged, then I can take a look at cleaning up these conflicts and getting this merged

**Comment by Caleb-T-Owens** [comment]
@ndom91 Yes, I've merged my thing. They are my conflicts so I'm happy to also resolve them if you want

**Comment by ndom91** [comment]
@Caleb-T-Owens okay I guess we're not in a hurry to merge this, right. I'll leave it for you for next week then :blush:

**Comment by mtsgrd** [comment]
I'm the one who dropped this 140+ file change unannounced, so I just went ahead and rebased it. 😏

**Pull request merged**
