### PR TITLE
Refactor credential check

### PR DESCRIPTION
**Pull request by mtsgrd**
- show tests while running (with indicator)
- incremental progress update

### CODE REVIEW

**Comment by PavelLaptev** [comment]
@mtsgrd Nice improvements! Could errors be different instead of just saying 'Error: authentication failed'?

image

**Comment by PavelLaptev** [comment]
@mtsgrd can you check my question above? 🙂

**Comment by PavelLaptev** [comment]
I didn't want to merge the PR before I fix the design.

**Comment by mtsgrd** [comment]
From a product perspective I prioritised landing the changes so we can iterate. Also, no release other than nightly has been published. ✌️

**Comment by PavelLaptev** [comment]
@mtsgrd got it, thanks!

**Pull request merged**
