### PR TITLE
feat: selectable commit title

### PR DESCRIPTION
**Pull request by meetmangukiya**
## ☕️ Reasoning

It is nice to be able to select and copy part or full commit subject

### CODE REVIEW

**Comment by PavelLaptev** [comment]
Thanks @meetmangukiya!

**Review by PavelLaptev — APPROVED** [review]

**Review by mtsgrd — CHANGES_REQUESTED** [review]
I tested this manually and it does not work. @meetmangukiya did you try it locally on your machine?

**Review by PavelLaptev — CHANGES_REQUESTED** [review]
Doesn't work for me as well

**Comment by PavelLaptev** [comment]
@meetmangukiya, we’ll add this functionality via a context menu. I’ll take care of it ASAP.

**Pull request closed without merging**
