### PR TITLE
fix `dev` script and DEVELOPMENT docs

### PR DESCRIPTION
**Pull request by kiprasmel**
i think in 746e8cca (new structure, 2023-09-06) you've migrated to workspaces,
but forgot to change the docs for running the application.

---

reading the DEVELOPMENT.md docs, i came accross an issue.

1. the `pnpm tauri dev` script did not work:

```sh
$ pnpm tauri dev

> git-butler-tauri@ tauri /Users/kipras/forkprojects/gitbutler
> tauri "dev"

thread '<unnamed>' panicked at src/helpers/app_paths.rs:85:5:
Couldn't recognize the current folder as a Tauri project. It must contain a `tauri.conf.json`, `tauri.conf.json5` or `Tauri.toml` file in any subfolder.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

2. alright, instead i tried running `pnpm dev`.

but it would only launch `dev` in `gitbutler-ui`,
which launches vite in a web browser, not the tauri window, so broken too:

```console
Unhandled exception TypeError: window.__TAURI_IPC__ is not a function
```

i.e., it only runs `vite dev`, not `tauri dev`.

3. trying to fix via `cd gitbutler-app && pnpm tauri dev`, nope - same issue as in (1).

... because pnpm scripts run in project root (i.e. `/` and not `/gitbutler-app`). i think if i had `tauri` installed and ran it directly there, it would've been fine, but i didn't have it installed.

4. if i cd inside `gitbutler-app` and run:

```sh
$ ../node_modules/.bin/tauri dev
```

everything works now.

5. well, shoes, proper fix then:

```sh
(cd gitbutler-app/ && ../node_modules/.bin/tauri dev)
```

apply it to the root package.json's "dev" script.

=> just gets stuck in infinite loop...

```sh
$ pnpm dev

> git-butler-tauri@ dev /Users/kipras/forkprojects/gitbutler
> cd gitbutler-app/ && ../node_modules/.bin/tauri dev

     Running BeforeDevCommand (`pnpm dev`)

> git-butler-tauri@ dev /Users/kipras/forkprojects/gitbutler
> cd gitbutler-app/ && ../node_modules/.bin/tauri dev

     Running BeforeDevCommand (`pnpm dev`)

> git-butler-tauri@ dev /Users/kipras/forkprojects/gitbutler
> cd gitbutler-app/ && ../node_modules/.bin/tauri dev

        Warn Waiting for your frontend dev server to start on http://localhost:1420/...
     Running BeforeDevCommand (`pnpm dev`)

^C ELIFECYCLE  Command failed with exit code 130.
 ELIFECYCLE  Command failed with exit code 130.
 ELIFECYCLE  Command failed with exit code 130.
```

...because i guess tauri's `dev` runs itself, and then the UI code via the root package.json's `dev` script, thus would end up in an infinite loop..

5. final fix - create a separate script for end-to-end dev, "devel", which works from project root, because avoids all of the issues above.

```json
    "devel": "cd gitbutler-app/ && ../node_modules/.bin/tauri dev",
```

it's ugly; too bad -- pnpm, unlike yarn v1, doesn't have `run --cwd` 🤷‍♀️

### CODE REVIEW

**Comment by kiprasmel** [comment]
strange. I'm on an M1 mac, sonoma 14.3.1

```sh
$ uname -a
Darwin M1.local 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000 arm64 arm Darwin

$ node -v
v20.11.1

$ pnpm --version
8.15.4
```

i re-did the setup in my ubuntu VM, and am still getting the same error.

**Comment by Qix-** [comment]
Can you try the following? Make sure to stash any changes you have before doing this or they may get wiped out.

```
git clean -dffx
pnpm i
cargo build --tests
pnpm tauri dev
```

**Comment by kiprasmel** [comment]
i did, same issue still. i also tried in my ubuntu VM and can reproduce.

this looks like a tauri issue; i see they've had multiple issues about this.

perhaps you have an older version of tauri-cli installed, either locally or globally? mine's 1.5.10

**Comment by kiprasmel** [comment]
nevermind, i found the issue.

in my $HOME directory, i have a dotfiles repository, though renamed from .git to .dotfiles, so that won't interfere with regular git repos.

however, i also have a ~/.gitignore file, which ignores everything by default.
tauri, for some reason, uses it, and won't work "if the tauri project is gitignored".
their behavior is incorrect ofc, because the global ~/.gitignore has nothing to do with the local repository. i'll create an issue/fix @ tauri; we can close this, thanks.

**Comment by kiprasmel** [comment]
i don't have `core.excludesfile` neither local nor global.
yep it's a bug in tauri. they do some weird stuff to find the root of the tauri-src directory where the tauri.conf.json lives.

**Comment by Qix-** [comment]
If you file a bug report over on the Tauri repo they'd probably appreciate it :) Good catch though.

There's nothing really actionable for us in this case though, so I'm going to go ahead and close this. Thank you for taking the time to investigate!

**Comment by kiprasmel** [comment]
alright, looks like tauri fixed the bug upstream, but only into the `dev` branch / `v2` beta:
https://github.com/tauri-apps/tauri/pull/8688

**Pull request closed without merging**
