### PR TITLE
Disable auto completions in branch filter field

### PR DESCRIPTION
**Pull request by Caleb-T-Owens**
* Related https://github.com/gitbutlerapp/gitbutler/issues/2709

## The problem

macOs spell checker is correcting words and capitalisation in the branch name filter.

Often we use incomplete words, non-word acronyms, and search terms that don't start with capitals, and it can be quite bothersome.

## The solution

The solution was to make use of the spellCheck property which does pretty much what it says on the tin

### CODE REVIEW

**Comment by krlvi** [comment]
Nice! Thank you for fixing this. By the way, if it's of interest, theres also this issue, which is very much the same thing, just in another place of the app: https://github.com/gitbutlerapp/gitbutler/issues/2728

**Comment by Caleb-T-Owens** [comment]
@krlvi Interesting. I would have thought that the commit message was one of the places you do want spell check on 😆.

Regardless, is it desired that spellCheck be false by default?

**Comment by krlvi** [comment]
I imagine a lot of people would wanna put things like names of subsystems, ticket numbers or other technical things in the commit messages, making spellchecking there more annoying than helpful.

**Comment by Caleb-T-Owens** [comment]
Makes sense - I'll go make sure that spellcheck=false is set everywhere then (taking a look, the git commit message is its own text area element)

**Review by krlvi — APPROVED** [review]

**Pull request merged**
