### PR TITLE
Prevent escape from closing "create pull request" modal that contains changes

### PR DESCRIPTION
**Pull request by simenbrekken**
## ☕️ Reasoning

After carefully crafting a pull request description for 10 minutes, the last thing you expect is for an accidental press of escape to close the dialog and destroy your stuff.

## 🧢 Changes

If title or body has been changed, prompt the user to confirm before closing dialog.

### CODE REVIEW

**Comment by Byron** [comment]
Thank you! I would think that pressing ESC was very intentionally linked, but I'd also expect it to ask to be sure the user is fine loosing changes they made.  CC @PavelLaptev as there might be other ways to prevent the user from accidentally loosing changes without completely disabling keys.

**Comment by simenbrekken** [comment]
> I would think that pressing ESC was very intentionally linked, but I'd also expect it to ask to be sure the user is fine loosing changes they made. CC @PavelLaptev as there might be other ways to prevent the user from accidentally loosing changes without completely disabling keys.

I've added a confirm dialog now that makes more sense.

**Comment by krlvi** [comment]
Maybe another way to solve this could be to save the PR description in progress in local storage, so that if one presses esc by accident, reopening the modal it will be pre-filled with the content before

**Comment by simen-ardoq** [comment]
> Maybe another way to solve this could be to save the PR description in progress in local storage, so that if one presses esc by accident, reopening the modal it will be pre-filled with the content before

Even better!

**Comment by PavelLaptev** [comment]
> Maybe another way to solve this could be to save the PR description in progress in local storage, so that if one presses esc by accident, reopening the modal it will be pre-filled with the content before

Agreed. I would be nice if we can do this.
@estib-vega what do you think, will you have time to implement this?

**Comment by estib-vega** [comment]
Sorry for the long wait! I somehow missed this completely

> > Maybe another way to solve this could be to save the PR description in progress in local storage, so that if one presses esc by accident, reopening the modal it will be pre-filled with the content before
> 
> Agreed. I would be nice if we can do this. @estib-vega what do you think, will you have time to implement this?

Yes! Let's do it

**Comment by simenbrekken** [comment]
Superseded by #5559, thank you @estib-vega

**Pull request closed without merging**
