### PR TITLE
Add a stack overview section to pr descriptions

### PR DESCRIPTION
**Pull request by mtsgrd**
When stacking pull requests we append/update a stack list when creating a new pull request, and the total count is >= 2. On deleting a branch from a stack we close any associated pull request, and update the descriptions to exclude it.

This is part of a stack made with GitButler:
- #5413 👈 
- #5475

### CODE REVIEW

**Review by Caleb-T-Owens — APPROVED** [review]

**Comment by mtsgrd** [comment]
Thanks @Caleb-T-Owens. @PavelLaptev, let me know when you've had a chance to look at this!

**Review by PavelLaptev — COMMENTED** [review]
Thanks, @mtsgrd! Looks good
_Just made a few UI updates_

**Comment by PavelLaptev** [comment]
If you don't mind, I also added a few things to the footer to improve readability.

image

**Comment by mtsgrd** [comment]
Awesome, thank you.

**Pull request merged**
