### PR TITLE
Change: preferred action for commit integration

### PR DESCRIPTION
**Pull request by PavelLaptev**
Currently, if there are no integrated remote commits, the preferred action is to `Force push`, which deletes remote commits. The preferred action in this case should be `Integrate upstream`.

image

### CODE REVIEW

**Comment by mtsgrd** [comment]
Sorry for the delay, I'm trying to figure what the appropriate event is for setting that preferred action. I don't think it's reactively to `requiresForce`, but more something like when it transitions from not having remote commits to having them. Also, this setting seems to be set at a project level, it feels like it would make sense to use branchId in the key instead?

**Comment by PavelLaptev** [comment]
@mtsgrd Thank you for helping me. Can I merge it, or do you want to change anything else?

**Comment by mtsgrd** [comment]
Sorry for the delay, let me change one more thing. I didn't want it setting
based on the parameter alone, but rather when it changes value from false
to true.

**Comment by mtsgrd** [comment]
Hey so we talked about this offline and consensus was that we want to hold off on this change. Just as you are likely to want to integrate upstream changes, it feels like it might be even more common that you have upstream changes because of undoing a commit.

Let's close this for now and solve it differently in the near future?

**Pull request closed without merging**
