### PR TITLE
Update app updater button copy

### PR DESCRIPTION
**Pull request by mtsgrd**

### CODE REVIEW

**Comment by mtsgrd** [comment]
@PavelLaptev this would be more accurate, what do you think? Download and install happen together, so currently, if you abort after download then the app has already been updated.
image

**Comment by PavelLaptev** [comment]
Looks good to me 🙂

**Comment by PavelLaptev** [comment]
@mtsgrd sorry for the late thoughts, but how about using 'Update to 0.5.692' to keep the copy shorter?

**Comment by mtsgrd** [comment]
I like it.

**Review by PavelLaptev — APPROVED** [review]

**Comment by PavelLaptev** [comment]
> I like it.

Cool :-) I'll leave it to you then

**Pull request merged**
