### PR TITLE
feat: add WebdriverIO based E2E test setup

### PR DESCRIPTION
**Pull request by ndom91**
## 🧢 Changes

- Add webdriver-io (https://webdriver.io) based E2E tests
	- Add initial `apps/desktop/wdio.conf.ts` and sipmle `apps/desktop/e2e/wdio/example.e2e.js` test to ensure the app is rendering and the `<body />` tag from SvelteKit's `app.html` is available.
	- Run via `pnpm test:wdio` 
- Add `.github/workflows/test-e2e.yml` wdio headless GHA
- Add `pnpm build:test` root npm script to simplify building a test build of the app. This uses a new `tauri.conf.test.json` which is basically the same as the dev `tauri.conf.json`, except for that it skips all the bundling (into `appimage`, `dmg`, etc.) in order to just generate the `./target/release/git-butler-dev` binary that we need to execute to run tests against

### Note

- Requires the following:
	- `tauri-driver` crate installed and binary avialable at `~/.cargo/bin/tauri-driver` 
		- `cargo install tauri-driver`
	- GitButler dev build available at `./target/release/git-butler-dev` (relative to root of repo)
		- `pnpm build:test` in root of repo

CC: @mtsgrd

### CODE REVIEW

**Comment by ndom91** [comment]
Someone made a little package (`@tauri-e2e/selenium`) to wrap some of the boilerplate of setting up selenium. I gave it a quick try and wasn't able to get nearly as far as I did with the "raw" selenium setup found in this PR. Using this wrapper pkg I ran into the same "capabilities don't match" error

Figured I'd mention it here though as notes / info for everyone:

- https://github.com/bukowa/tauri-e2e
- https://bukowa.github.io/tauri-e2e/documents/2__Quickstart_Guide.html

**Comment by ndom91** [comment]
Notes:

- CI: https://github.com/ivangabriele/docker-tauri/blob/b6eaef18760e30cb5e4fa88b2b4bfd77836cc36e/README.md?plain=1#L115-L127
- Pretty sophisticated setup: https://github.com/dev-protocol/nym/blob/0f6f47c5ac48cfff614893fadf00b7f35bdbfb4e/nym-wallet/webdriver/README.md
-

**Comment by ndom91** [comment]
Current status:

- Tried the webdriver-io variant of the Tauri testing. Got everythign up and running as well, but running into the same issue as with the selenium setup. In that the test file seems to finish executing before GitButler is even started. Very suspicious that its the same issue..  :thinking:

image

**Comment by ndom91** [comment]
Same deal in GHA :thinking: 

image

> https://github.com/gitbutlerapp/gitbutler/actions/runs/10202669578/job/28227314397?pr=4561

**Comment by mtsgrd** [comment]
This is really great @ndom91!
 
Maybe you've already got this planned, but can we re-use the `init-env-node` and `init-env-rust` workflows for setting up node and rust?

**Comment by ndom91** [comment]
> This is really great @ndom91!
> 
> Maybe you've already got this planned, but can we re-use the `init-env-node` and `init-env-rust` workflows for setting up node and rust?

Hmm so I think this specific testing workflow doesn't need a good bit of what the `init-env-node` one does and the `init-env-rust` one just seems to print out `--version` for a bunch of tools (?) haha. 

This `test-e2e.yml` setup process is so simple I'd prefer to just keep it this way if the small bit of duplication doesnt bug you guys haha

**Pull request merged**
