### PR TITLE
Refactor PR templates to use front end persisted store

### PR DESCRIPTION
**Pull request by mtsgrd**
Fixes issue related to git host -> forge renaming in #5367.

### CODE REVIEW

**Review by Caleb-T-Owens — APPROVED** [review]
LGTM

**Review by estib-vega — APPROVED** [review]

**Comment by mtsgrd** [comment]
I changed everything about this PR, instead of fixing the issue I refactored PR templates a bit. @estib-vega could you apply this branch and double check that it works correctly?

**Comment by krlvi** [comment]
Does this fix the 
```
Invalid args `gitHost` for command `update_project_git_host`: command update_project_git_host missing required key gitHost 
```
issue?

**Comment by mtsgrd** [comment]
It does. Sorry for the delay, I changed my mind a few times about what I actually needed to fix. In the end, @estib-vega and I agreed that storing the forge type and template path under projects.json can be replaced with a `persisted(...)` store in the front end.

**Pull request merged**
