### PR TITLE
UI fixes: Hunk preview and checkboxes

### PR DESCRIPTION
**Pull request by PavelLaptev**
Changes:
- Remove duplicated hunk info and replace bare text and icons with tooltips with infomessages
- There was a shift issue with borders on scroll
- Fix the hunk header paddings
- Replaced `box-shadow` with borders. Looks like it's not longer an issue
- Draggable icon update
- Selected hunk colors update

Before:

https://github.com/user-attachments/assets/e947621b-c352-4fd3-8dfd-125d0997b2f6

After:

https://github.com/user-attachments/assets/2d30826b-d4ef-42f9-ad31-690bab8ad3ed

### CODE REVIEW

**Comment by estib-vega** [comment]
@PavelLaptev Thanks for the fixes! 

One thing though, I see something familiar on the after video haha.
I was fighting that weird table borders behavior in that scrolling would move the content but not all borders. 

I think I know how to fix that. 

Would you be ok if I add it as a commit on top?

**Comment by PavelLaptev** [comment]
Yes, let's try. Is it too hacky? Borders was the reason why I gave up  and revert the old implementation, didn't want to over complicate things.

**Comment by estib-vega** [comment]
> Is it too hacky?
>

Some parts are just about re-adding the inset box-shadows and other about having absolutely positioned divs.
The latter is the part that requires dynamically set values.

What do you think?

**Comment by estib-vega** [comment]
https://github.com/user-attachments/assets/beee0a80-34f5-4c5f-89fc-14f6898336de

What about this?

**Review by estib-vega — APPROVED** [review]
Approved in order to get it on the release :)

**Comment by PavelLaptev** [comment]
> Approved in order to get it on the release :)

@estib-vega Thanks! I'll check your implementation later.

**Pull request merged**
