### PR TITLE
fix: faster e2e runs

### PR DESCRIPTION
**Pull request by ndom91**
- Follow-up from: https://github.com/gitbutlerapp/gitbutler/pull/4692
- Use debug build for test to improve build time

### CODE REVIEW

**Comment by Byron** [comment]
Thanks for picking this up! I gave up a little quickly there 😁.

**Comment by ndom91** [comment]
@mtsgrd what did you mean by [your comment](https://github.com/gitbutlerapp/gitbutler/pull/4692#issuecomment-2290874441) regarding `gitbutler-git` exactly?

**Comment by mtsgrd** [comment]
Try adding another step in test-e2e.yaml that runs `cargo build -p gitbutler-git`. I ran into this a few days ago, see this discord message: https://discord.com/channels/1060193121130000425/1204524097241878629/1271551056102424627

In the logs for the e2e run you see this error, albeit a bit hard to find:
image

**Comment by ndom91** [comment]
Hmm, even with an additional `cargo build -p gitbutler-git` step, the `Build CLI` and `Build Tauri` (rest of application) steps don't seem to be reusing any of one anothers work.

Previously (in master), building CLI generally takes ~30s and building Tauri app takes ~4m for a total of ~4m30s. In this PR, the two/three steps still take ~4m30s in total, just split up differently.

I've passed `--profile dev` to each build cmd btw

**Review by mtsgrd — APPROVED** [review]

**Comment by ndom91** [comment]
@mtsgrd do you want to merge this as-is? Currently there is no real gain in overall duration. The current state is approximately like this:

Before:
- Build CLI: 30s
- Build Tauri: 4m

After:
- Build gitbutler-git: 30s
- Build CLI: 2m
- Build Tauri: 2m

I'm a bit out of my depth here with Rust build tooling, so if anyone else has a good idea I'm happy to try it, but otherwise I think my time is best spent elsewhere :+1:

**Comment by mtsgrd** [comment]
Hmm, I'd say it's better to test the release build if we don't see a big gain in performance? It's testing something closer to the thing we distribute.

**Comment by ndom91** [comment]
> Hmm, I'd say it's better to test the release build if we don't see a big gain in performance? It's testing something closer to the thing we distribute.

Yeah agreed. I'll close this PR then :+1:

**Pull request closed without merging**
