### PR TITLE
Delete entry from .toml file when branch is integrated

### PR DESCRIPTION
**Pull request by mtsgrd**
- virtual_branches.toml file was full of old entries

### CODE REVIEW

**Comment by mtsgrd** [comment]
@krlvi @Caleb-T-Owens I think we might need some retroactive cleanup if I'm correct about this change?

**Comment by Caleb-T-Owens** [comment]
@mtsgrd the reason we don't just delete the entries from virtual_branches.toml is so that we can re-use the fancy name when the branch gets re-applied.

If we want to "garbage collect" entries, we ought to do it when there are no local or remote reference which relate to a given name

**Comment by Caleb-T-Owens** [comment]
(or we have to accept that the fancy names will be lost)

**Comment by mtsgrd** [comment]
> If we want to "garbage collect" entries, we ought to do it when there are no local or remote reference which relate to a given name

This PR changes the code to delete the entry when we detect upstream has been integrated, and after we have deleted the local branch. In this case surely it doesn't make sense to retain the fancy name? In our case the remote branch is also automatically deleted after merging to master, so unless I'm mistaken, the only reference left is in fact in that toml file.

**Review by Caleb-T-Owens — APPROVED** [review]

**Comment by mtsgrd** [comment]
@ndom91 I just noticed vercel deployed here based on a change in an .rs file. What options did we have for fixing this?

**Comment by ndom91** [comment]
> @ndom91 I just noticed vercel deployed here based on a change in an .rs file. What options did we have for fixing this?

It seems to always deploy once for the first commit of a branch, since it doesn't know which commit to compare that against. We can pass the `turbo-ignore` cli a `--fallback` ref though for those situations. 

See my comment here: https://github.com/gitbutlerapp/gitbutler/pull/4664#issuecomment-2281203216

**Pull request merged**
