### PR TITLE
feat: bump tauri to 1.8.0

### PR DESCRIPTION
**Pull request by ndom91**
## ☕️ Reasoning

- The tauri folks have merged a few PR's prepping the updater for moving from tauri v1 to tauri v2, see: https://github.com/tauri-apps/tauri/pull/10938#issuecomment-2351551535
- They explicitly mentioned in their Discord, however, that we should definitely upgrade to `1.8.0` first and then to `2.0+`. 

## 🧢 Changes

- Cargo: Bump `tauri@1.8.0`
- Node: Bump `@tauri-apps/cli@1.6.2`

### CODE REVIEW

**Review by amrbashir — COMMENTED** [review]
Hey, apologies but I forgot to mention that you should also update the tauri CLI, it is a must if you are using NSIS installer, but even if not, you probably should still update it for good measure

**Comment by ndom91** [comment]
@amrbashir great, thanks for reaching out!

**Review by krlvi — APPROVED** [review]
lgtm

**Comment by krlvi** [comment]
merging cause i would like to test this on the nightly now

**Pull request merged**
