### PR TITLE
 - Add `Remove this project ...` button with not on git butler branch screen

### PR DESCRIPTION
**Pull request by AbhishekThorat**
Fix for #2735 
Quick screenshot after changes - 
Screenshot 2024-02-19 at 9 39 15 PM

### CODE REVIEW

**Review by krlvi — APPROVED** [review]
thanks!

**Comment by AbhishekThorat** [comment]
> thanks!

Thanks for review @krlvi, 
Apologies but I added [one minor commit](https://github.com/gitbutlerapp/gitbutler/pull/2818/commits/dea2b64b6f2b33467846977c75402eab802881cf) after your review. (my bad but I updated variable representing deleting state.)

**Comment by PavelLaptev** [comment]
Thank you for your contribution @AbhishekThorat 
I just made a few UI updates

**Review by PavelLaptev — APPROVED** [review]
Thank you for your contribution @AbhishekThorat
I just made a few UI updates

**Pull request merged**
