### PR TITLE
GitButler badge

### PR DESCRIPTION
**Pull request by kjy5**
A user on Discord had this feedback:
>Free as in freedom. I've seen an option that credits GitButler in your commits which can be turned off by having a subscription if I got it correctly. I understand that devs want their app to be mentioned everywhere possible and supported by all it's users but firstly, it just clutters the commit history and gives unneeded information for anyone else reading the commit message, secondly, the app is just not considered free anymore, it may be just be a single line mentioning GB but I'm not going to use it like that.

I think one easy, cool, and effective way to show off the usage of GitButler is through badges on README's. Like this:

[![GitButler](https://img.shields.io/badge/GitButler-blue?logo=data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAmmVYSWZNTQAqAAAACAAGARIAAwAAAAEAAQAAARoABQAAAAEAAABWARsABQAAAAEAAABeASgAAwAAAAEAAgAAATEAAgAAABUAAABmh2kABAAAAAEAAAB8AAAAAAAAAEgAAAABAAAASAAAAAFQaXhlbG1hdG9yIFBybyAzLjUuNgAAAAKgAgAEAAAAAQAAAECgAwAEAAAAAQAAAEAAAAAAl9pxFAAAAAlwSFlzAAALEwAACxMBAJqcGAAAA2xpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDYuMC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8ZXhpZjpQaXhlbFlEaW1lbnNpb24%2BNjQ8L2V4aWY6UGl4ZWxZRGltZW5zaW9uPgogICAgICAgICA8ZXhpZjpQaXhlbFhEaW1lbnNpb24%2BNjQ8L2V4aWY6UGl4ZWxYRGltZW5zaW9uPgogICAgICAgICA8eG1wOkNyZWF0b3JUb29sPlBpeGVsbWF0b3IgUHJvIDMuNS42PC94bXA6Q3JlYXRvclRvb2w%2BCiAgICAgICAgIDx4bXA6TWV0YWRhdGFEYXRlPjIwMjQtMDItMTNUMTY6Mjg6MzQtMDg6MDA8L3htcDpNZXRhZGF0YURhdGU%2BCiAgICAgICAgIDx0aWZmOlhSZXNvbHV0aW9uPjcyMDAwMC8xMDAwMDwvdGlmZjpYUmVzb2x1dGlvbj4KICAgICAgICAgPHRpZmY6UmVzb2x1dGlvblVuaXQ%2BMjwvdGlmZjpSZXNvbHV0aW9uVW5pdD4KICAgICAgICAgPHRpZmY6WVJlc29sdXRpb24%2BNzIwMDAwLzEwMDAwPC90aWZmOllSZXNvbHV0aW9uPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KPIpwGwAAAu5QTFRFAAAAAAAAAAAAMzMzKysrQHBgecLCZqOZZqOjb7Oqa62lgNrSh9rSg9bPg9HRfM3NgM7IZKKiZKaigdLOgNLPiuPdiuTfieHehdrVhdrWjujjjefjjejjiODbiOHcjenkkvDqk%2FLtlPPuke%2FqkvHskO3oke3oke7pke%2FqkO3oke3oku%2FqAAAAAAEBAQEBAQIBAQICAQMDAgMDAgQDAgQEAwQEAwUFBAYGBAcGBQcHBQgIBQkJBgkJBgoKBwoKBwsLCA0NCQ8PChAQCxAQCxEQCxERCxIRDRUUDxcWDxcXDxgXDxgYDxkZEBgXEBkYEBkZERwbEh0cEh4dEx0dFB4eFSEgFiIhGCUkGCcnGScnGSkoGicnGignGigoGywsGy0rHSwrHSwsHS0sHTAvHy8vHzAvHzIxIDIxIDQzIjU0IjU1IjY1Izc2JDg3JDk4JTk4JT07JT08Jj49Jz08KD49KkJAK0NCK0VEK0ZELEVELEZELUZELUhGLkhHL0lIMExKMUxKM09OM1BONFFPNFFQNVRSNlVTNlVUOFhWOVlXOVlYOltZOlxaOmBeO1xaPWBePmFfPmJgP2ZkQGVjQGdlQWZkQWdlQWlmQmhlQmhmQ2lnRW1qRW1rRm9sRm9tR3JwR3NxSHJvSHJwSXRxS3d1THh2THl2Tnt5T317UoKAU4SBU4iFVIaDVIqHVYeEVYeFV4uIWIuIWZOQWpSRW5CNW5GOW5KPXJKPXJiVXZSRXZqWXpaTXpqXXpuYX5iVYZ%2BcYaCcYaCdYaGdYpyYYpyZY56bZqOfZqOgZqekZ6WhZ6WiZ6mmaKejaKmmaKyoaammaayoa6ypbbCsbrCtbrGtb7aycLaycLi0cbq2cre0cri0c7q3dLu3dLy5dby4db25ecXBesbCfMrGfMvGgdTQgtXQgtXRg9fTg9jThtvWiODbiODciuTfi%2BXgjObhjObijOfijefijejjjejkjunkjurlj%2Bvnj%2BznkOznkO3oLql%2F9wAAACx0Uk5TAAECBQYQFRkZHh8iIiUnKSpCQklKkJCRlpa0tcrU1Ov3%2Bvr7%2B%2Fz8%2FPz%2B%2Fv7%2Bt0HzAAADUklEQVRYw2NggANGBkYWVg4uHl4%2BfgGsgJ%2BPl5uTnZUFqJABEzAyC0rIKigpqiirq2vgAOrqyiqKSgpyEkLM6EYwiUjLa%2F%2FQ%2FEkU0PyhLS8lzISsn01M7cdP0oCqKBuSATJaP0kGWjII%2B2V%2BkgVkoG5gEtcizwAtMUg4CKv%2BJBOoiYDjT4pc%2FT9%2FSINik1mebAN%2ByjMDHSCkTb4B2oJAJ0j8IN%2BAHxJAF8hpkm%2BApiwjA4vCTwqAAgsDqxIlBiixMrArUmKAIgcDpwolBqhwMXArU2KAMg8Drzqc9%2BnZk3eE9bx78uwTnKPOy8CHMKDX1ib5BCH9p5Nt7XsRBvAx8GvAOG8sdHR0DIr2f8Gt%2B8uhQiM9PT3LNzABDX4GAbgBz3XAQC%2FwOg6PvL8RaKAHBi%2FgBghgGqCjYxS%2F5ztm%2Bv5xosLTCqJf7zl%2BA4CuSNvzFlX7p6vT8xNDXEyJNEBHR9fx3EeE9q%2BP5%2FQ1lWXH%2BNsRbQAwOKNWf4F45NvDfSsWTe1sKEkNdTUiJgzgHona9Bpo%2B9NLR7avWz5vYmt1TrSvFfEuAHvEbO%2FL%2B7cunzmyZdWSWd0NxUnBDgYkuABsRNCUu3eunNq3ccW8%2FpbS9DA3I5JcAAbeC85fPLp15eLJ7VWZ4e6mJLoA4oxtx3euWTKzozY30sOcHAN0ak7uXr9sVlddfqyXJeleABlwavf6pbM66%2FKgBpDqAr1tx4BemIHwAmku8JkPDMQtwEBsgwciCQboBU26e%2FvyyX0bgNHYDIxGV9KiUddk78t7Ny9hJCQiDdCL2PwKnJQPA5Py3AmtlTmRpCRlg6i10Mz0%2FcG%2BFQundtaXpMAyEzHZ2enCB6Ts%2FGh2T2NZVqQfsdlZP2MXWoHy%2Bdq0vIQQZ1OiijTjuB3fMUvE72fLPSz1iDBANwBXofrhRhCWQhWtWDcsOIivWD9QhFGso1Qs1smnCVUsJ9ArFoqrNh7KKlduBi7KqndOBg5KGxgUN3EobmQxylLSzJOjRkNTkJKmrhAj5Y1tBkZp8v0gBe68iaiRq19VGNLlESO3yyPKRJ1OF%2BXdPqAbREnteP1QE2ND6foKS5HW9ZUWYcLofAtJyhHX%2BZaVEGTG2n8Hd%2F85ufF1%2F3m4ONC6%2FwDLTzyPVybyPQAAAABJRU5ErkJggg%3D%3D&color=7684ff)](https://gitbutler.com/)

This could be considered an alternative to the committer thing (show proof of usage on a public repo etc. to qualify for turning this off). Some repo's may prefer this method over using the committer.

Summary of changes:
- Created Shield.IO badge
- Added a version to README (trying to follow the style already set)
- Added instructions at the bottom for how to add it to your own projects

Questions:
- The logo was a base64 encoding which is kinda ugly in the README, feedback on how to make that better is welcome.
- Instruction text suggestions are welcomed as well.

### CODE REVIEW

**Comment by PavelLaptev** [comment]
@kjy5 thanks for your contribution! I've made a slight adjustment to the badge style to better align with our brand palette.

[GitButler](https://gitbutler.com/)

**Comment by kjy5** [comment]
That looks even better!

**Comment by krlvi** [comment]
Hey @kjy5! First of all, thank you for this idea and contribution, it looks really cool! 

I just wanted to clarify that the option to turn off the committer mark, was not gated by being a supporter — we were sharing it proactively with anybody on Discord.
With this said, I agree that the committer thing could be adding clutter, so I am making it disabled by default with this PR: https://github.com/gitbutlerapp/gitbutler/pull/2690 

And there is a config for anybody who wishes to enable it :) 
Cheers!

**Review by krlvi — APPROVED** [review]

**Comment by kjy5** [comment]
Thanks! Yeah I saw the command in your reply on discord 👍 the committer mark didn't bother me but I know some orgs care.

**Pull request merged**
