### PR TITLE
fix: Update cleanUrl method to handle ssh URLs

### LINKED ISSUE #3808: Can not open remote url while using `ssh://` as remote url
One of my git project's remote url is: `ssh://git@xxx/xxx/xxx.git`, and i can not open remote url.

CleanShot 2024-05-22 at 13 49 40

Maybe we should handle it here?

CleanShot 2024-05-22 at 13 49 12

### PR DESCRIPTION
**Pull request by lisiur**
fix: #3808

### CODE REVIEW

**Comment by Caleb-T-Owens** [comment]
Thanks for the contribution! 🎉 

Now that the method is manipulating the URL in three different ways, it would be great if there were some test cases for it. If you are up to it, could you move the method so its an exported function from `types.ts`, and then write some tests in a `types.test.ts` file? If you don't want to/have time to, I'm more than happy to write them 👍

**Comment by Caleb-T-Owens** [comment]
If you're using VSCode, the following configuration should help with linting & formatting btw:
```json
{
  "eslint.validate": ["svelte"],
  "eslint.workingDirectories": ["app"],
  "editor.formatOnSave": true,
  "prettier.configPath": "app/.prettierrc",
  "prettier.useEditorConfig": false,
  "svelte.enable-ts-plugin": true,
  "svelte.plugin.svelte.defaultScriptLanguage": "ts",
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "typescript.preferences.importModuleSpecifier": "non-relative",
  "javascript.preferences.importModuleSpecifier": "non-relative",
  "[rust]": {
    "editor.defaultFormatter": "rust-lang.rust-analyzer"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
}
```

**Comment by lisiur** [comment]
Sure, I'll add some tests.

**Comment by lisiur** [comment]
I moved it to `utils/url.ts` and wrote some tests in `utils/url.test.ts`.

**Comment by Caleb-T-Owens** [comment]
Thanks @lisiur, that is a good home for it 👍

**Comment by Caleb-T-Owens** [comment]
@lisiur, are you "lisiurday" on discord?

**Comment by lisiur** [comment]
Yes, that's me

**Pull request merged**
