### PR TITLE
fork exec with futures instead of tokio

### PR DESCRIPTION
**Pull request by krlvi**
@Byron do you think its a good idea to just block for the fork exec with futures instead of starting a whole tokio thing?

### CODE REVIEW

**Comment by krlvi** [comment]
okay probably this doesnt work

**Review by Byron — COMMENTED** [review]
I saw that too but was thinking that maybe these futures need a tokio executor to work, which is why I didn't dare to change it.
However, it seems to work without which is a little unexpected, but very welcome, too.
Edit: It seems it was needed after all, but see below, `tokio` shouldn't be needed, nor should async be.

My feeling is that this (ssh prompt handling) can be done entirely without async and the respective complications, it feels like it's much more than it has to be, but I will need to validate that hunch (one day).

**Comment by krlvi** [comment]
it worked in my manual testing of it but some tests failed in CI... im relatively confused

**Comment by Byron** [comment]
Every tokio-future, i.e. every async call in `tokio` needs the tokio runtime to work. In the application, that's the case naturally , but in stripped-down test environments that's not the case, particularly now that `tokio::test` isn't used anymore.

**Pull request closed without merging**
