### PR TITLE
feat: new stacking ui commit lines

### PR DESCRIPTION
**Pull request by ndom91**
## ☕️ Reasoning

- More initial stacking UI changes including:
	- Commit Lines
	- Commit Card
	- Commit List

## 🧢 Changes

- Since we want to maintain both functionalities for now, I created a second version of `packages/ui/commitLines` in `packages/ui/commitLinesStacked/*` as well as second copies of the `CommitList` and `CommitCard`. This will should be relatively easy to switch over once the time comes.
- Still toggle-able via the feature flag in the global settings UI as well as via the `stack` keyboard shortcut

## 📺 Current Screenshots

<table>
<tr>
<td>

image

</td>
<td>

image

</td>
</tr>
</table>

### CODE REVIEW

**Comment by ndom91** [comment]
Current:

<table>
<tr>
<td>

image

</td>
<td>

image

</td>
<td>

image

</td>
</tr>
</table>

**Comment by PavelLaptev** [comment]
@ndom91 looks like there is an error in commits icons.
This is not how "remote" commits should look like. This is for local + "shadow" commits

image

Here is the legend:
image

**Comment by PavelLaptev** [comment]
@ndom91  can you please add stories for new lines, so I can test it?

**Comment by ndom91** [comment]
Are you sure that's a remote-only commit? If so, it probably just got classified incorrectly, I definitely had remote only separately appearing as it should. I'll take a look tmr, and I can add stories, no problem 👌

**Comment by PavelLaptev** [comment]
> Are you sure that's a remote-only commit? If so, it probably just got classified incorrectly, I definitely had remote only separately appearing as it should.

It could be not remote only, but this representation for two commits — "shadow" + another commit type
When I hover over commit circles, there also should be a tooltip with a short info about the commit.

image


In my case I didn't have "shadow" commits I just pushed my changes. so it should be "remote" type with one circle

**Comment by PavelLaptev** [comment]
Probably you were confused because in the legend I call "local and remote" as just "remote". Fixed this

image

**Review by PavelLaptev — APPROVED** [review]

**Comment by PavelLaptev** [comment]
@ndom91 I made my fixes and there are few left. 

- The last card in the commit group should have the dashed line
image

- Shadow commit. On hover, I added this placeholder text, but it should be a shadow commit SHA 
image

you can merge the PR when you ready. However there are fixes that I didn't make because I need the second PR for it (eg. I need a branch header).

**Comment by ndom91** [comment]
Yeah there's still a few things to finish. Thanks for your updates ❤️ 

Will work on the rest the next few days

**Comment by ndom91** [comment]
Fixed the following issues:
- Original (non-stacking) line color issues you pointed out
- Dashed bottom line
- remote and shadow dots tooltips

I'll merge this one now then and we can continue with [the next PR](https://github.com/gitbutlerapp/gitbutler/pull/4978). That one's definitely still on Draft though, give me some time to finish it up :wink:

**Pull request merged**
