### PR TITLE
Let libgit provide context

### PR DESCRIPTION
**Pull request by Caleb-T-Owens**
I thought I'd just make this a draft PR in case anyone wants to take it further before I have time to continue working.

## Current progress

- Removed all context-generating rust code
- Asked libgit2 to provide context

This has actually (in some cases surprisingly) solved the problem of committing different parts of the same file to different branches.

There however is just one main problem:

- Dragging files and hunks between branches after you've made commits higher up doesn't seem to work.

### CODE REVIEW

**Comment by Caleb-T-Owens** [comment]
Looking at the code for transferring hunks - it looks like it tries to match up hunks by their start and end lines, but this is problematic as the line numbers are currently scoped to the state of the file on the branch, which it struggles with when there are changes nearer the top of the file.

We need to change the fn eq() to account for a "normalised" position of the hunks

**Comment by krlvi** [comment]
fyi @Caleb-T-Owens i have now merged this one https://github.com/gitbutlerapp/gitbutler/pull/2908

**Comment by Caleb-T-Owens** [comment]
Fantastic @krlvi! Looking forwards to trying that out. Shall I close this PR?

**Comment by krlvi** [comment]
> Fantastic @krlvi! Looking forwards to trying that out. Shall I close this PR?

i think we can close it because this will not conflict quite badly.

**Pull request closed without merging**
