### PR TITLE
Add character count feedback for commit title

### PR DESCRIPTION
**Pull request by dinolindlau**
- display the remaining character count, advice is 50
- only available for the first line of the commit, commit title

https://github.com/gitbutlerapp/gitbutler/assets/61562467/53df04ab-13d3-409d-b663-548f3efc4216

### CODE REVIEW

**Comment by PavelLaptev** [comment]
@6abotage thanks for the PR!
I like the idea, but there are a few things I'd like to fix before merging. 
Not everyone may get what '50' means. So, there should be a tooltip. But actually, I'm also thinking of a different approach, maybe being less strict.
The easiest way is to separate fields by default. 
Let me think it over; let's keep this PR open.

**Comment by 6abotage** [comment]
Ofcourse, I would be glad to hear about your thoughts on design and UX and can change the implementation accordingly

**Comment by PavelLaptev** [comment]
Cool, thanks :-) @krlvi is also working on the commits templates feature, so I'll collaborate with him to avoid interfering with his concept.

**Comment by PavelLaptev** [comment]
@Qix- I also like this. Commits templates delayed, so I'll try to check this PR this week.

**Comment by 6abotage** [comment]
Just ping me, if I can help or implement something

**Comment by PavelLaptev** [comment]
@6abotage @Qix- @mtsgrd, what are your thoughts on this concept?
I want to combine it with @6abotage's PR and display the counter as well.

Branch for testing https://github.com/gitbutlerapp/gitbutler/compare/master...commit-message-concept

Here's how it works:

- Users start by writing the 'Commit title' until they hit 'Enter.'
- Afterward, we show the commit description field.
- The idea is to enhance commit writing by visually differentiating the summary from the commit message via UI. There are some corner cases, but I can cover those later.

https://github.com/gitbutlerapp/gitbutler/assets/18498712/030bc886-7b8c-4a2a-b8e4-c561caa40a74

**Comment by PavelLaptev** [comment]
@6abotage let's close this PR and move the discussion to this one https://github.com/gitbutlerapp/gitbutler/pull/3134
Could you please check if it solves the issue for you?

Changes I made:
- Added summary and description fields.
- Implemented a tooltip to display when the summary length exceeds a certain limit, instead of using a counter. I opted for a tooltip in order to minimize distraction, and the counter feels more restrictive.

**Comment by 6abotage** [comment]
That's alright, let's close this one.

**Pull request closed without merging**
