### PR TITLE
Add authors in Packager.toml

### PR DESCRIPTION
**Pull request by namanlp**
Hi awesome GitButler team!

I am Naman Garg, and am working with [tauri-apps](https://tauri.app/) and [CrabNebula](https://crabnebula.dev/), and @naman-crabnebula is my work account.

( I am introducing myself because you might see a few pull requests by me in future as well )

So, this Pull Request adds the `Maintainer` field in the `.deb` package, and hence, close the issue https://github.com/gitbutlerapp/gitbutler/issues/2542

**Note :** I filled the `authors` as per my understanding from repo. Have a look before merging.

### CODE REVIEW

**Review by krlvi — APPROVED** [review]
Thank you Naman for this! This is, in fact, the first contribution from outside the core team, much appreciated!

**Review by Qix- — APPROVED** [review]

**Comment by namanlp** [comment]
Hi @krlvi , I am glad to hear that 🎉 

I hope there will be many more contributors soon!

**Comment by Qix-** [comment]
Whoops, caught something - could you change it to `gitbutler@gitbutler.com`?

Thanks so much for the PR!

**Comment by Qix-** [comment]
Thank you :) Will merge on green!

**Comment by Qix-** [comment]
Seems actions are stalled, something might have gotten screwed up when we changed visibility. Investigating really quick.

**Comment by Qix-** [comment]
Thanks again!

**Comment by naman-crabnebula** [comment]
You're welcome!

Btw, just noticed that commits aren't squashed on merging. You might want to do that.

**Comment by Qix-** [comment]
Yeah I noticed that as well, we'll probably adjust the defaults as we get situated into the public operating mode. Thanks for the heads up :)

**Pull request merged**
