### PR TITLE
feat: hide contextMenu items that cant be activated and convert ContextMenuItem to runes

### PR DESCRIPTION
**Pull request by ndom91**
## ☕️ Reasoning

- Hide series context menu items that would normally be disabled

## 🧢 Changes

- Convert ContextMenuItem to runes
- Update all uses of `ContextMenuItem`

### CODE REVIEW

**Comment by krlvi** [comment]
Maybe copy could be simpler, eg. "Not undateable after pushing" - what do you think? As a native english speaker

**Comment by PavelLaptev** [comment]
We shouldn't display "rename" at all if it was already pushed

**Comment by PavelLaptev** [comment]
another thing. No one doing tooltips in context menus. So find another way

**Comment by PavelLaptev** [comment]
@krlvi cc

**Comment by ndom91** [comment]
@PavelLaptev yeah good call, so I've just hidden the options that used to be disabled. So now invalid options aren't shown when they can't be clicked. What do you think?

**Review by PavelLaptev — APPROVED** [review]
thanks! Looks good :-)

**Pull request merged**
