### PR TITLE
Series UI: update copy to speak about branches

### PR DESCRIPTION
**Pull request by krlvi**
At least for now, its more familiar terminology

Also update the empty state copy:
Before:
image

After:
image

### CODE REVIEW

**Comment by krlvi** [comment]
@PavelLaptev FYI updated copy (so that you can update figma)

**Comment by ndom91** [comment]
Btw the empty state here isn't a dropzone yet. 

I have a WIP branch for it, but we have it on phase2 atm. Should we bump it up in priority?

**Comment by krlvi** [comment]
>  Should we bump it up in priority?
nah. i think i just needed some reasonable copy

**Comment by PavelLaptev** [comment]
lgtm, thank. Updated this in figma as well

**Comment by ndom91** [comment]
> > Should we bump it up in priority?
> 
> nah. i think i just needed some reasonable copy

Okay but you changed it to "..or drag and drop commits here", but that's not possible yet

**Comment by krlvi** [comment]
> > > Should we bump it up in priority?
> > 
> > 
> > nah. i think i just needed some reasonable copy
> 
> Okay but you changed it to "..or drag and drop commits here", but that's not possible yet

I needed some extra text so that it doesnt seem empty. We can fix the code to align with the copy early next week

**Comment by ndom91** [comment]
> I needed some extra text so that it doesnt seem empty. We can fix the code to align with the copy early next week

Okay sounds good :thumbsup:

**Review by ndom91 — APPROVED** [review]

**Pull request merged**
