### PR TITLE
Add git credential checker to project setup

### PR DESCRIPTION
**Pull request by mtsgrd**
This is meant to help with the most frequent support requests, problems with pulling from and pushing to a git remote.

### CODE REVIEW

**Comment by PavelLaptev** [comment]
@mtsgrd Looks good to me 🙂 I only made a few style changes. Feel free to merge it

**Comment by krlvi** [comment]
you can use this API: https://github.com/gitbutlerapp/gitbutler/pull/3059
in conjunction with the fetch API. 

Note that these require the target branch to be set before executing.
So i imagine, after the target branch has been set, the UI will run both of these, and then display the outcome, e.g. 
was able to fetch but was not able to fetch. heres some options you can try out, you can always skip this and change in the project settings.

**Comment by PavelLaptev** [comment]
@krlvi this change requires a little design update. The current UI only shows it in general

**Comment by krlvi** [comment]
Alright! I will leave you guys to take care of it

**Comment by PavelLaptev** [comment]
@mtsgrd here is updated design in Figma https://www.figma.com/file/FbeLt0yjY9RiNn8MXUXsYs/Client-Design?type=design&node-id=1752%3A73155&mode=design&t=sNYIyHKPjiIBJLdH-1

And the settings page as well — https://www.figma.com/file/FbeLt0yjY9RiNn8MXUXsYs/Client-Design?type=design&node-id=1513%3A57296&mode=design&t=sNYIyHKPjiIBJLdH-1

image

**Comment by krlvi** [comment]
APIs for testing:

push test:
```
invoke<string>('git_test_push', {
			projectId: projectId,
			remoteName: remoteName,
			branchName: branchName
		})
```

fetch test:
```	
invoke<string>('git_test_fetch', {
			projectId: projectId,
			remoteName: remoteName,
		})
```

**Comment by mtsgrd** [comment]
On this PR it should be working in the project settings. Will add to the project setup page tomorrow.

**Comment by mtsgrd** [comment]
@krlvi @PavelLaptev fyi I'm going to merge this now. It doesn't yet show any error message, but let's add that as a next step.

**Comment by mtsgrd** [comment]
Hmm - I've missed something. Something about a redirect just after adding project, I will fix within a couple of hours max.

image

**Comment by mtsgrd** [comment]
Landing a fix in #3078.

**Pull request merged**
