### PR TITLE
scrollbar-updates

### PR DESCRIPTION
**Pull request by PavelLaptev**
Added new items to user settings — ability to show scrollbar if scroll viewport hovered.

Made changes to the scrollbar component in order to support this. Also made UX improvements for scrollbar.

https://github.com/gitbutlerapp/gitbutler/assets/18498712/3dcc4ba6-6492-43b8-808d-8535dec07b61

### CODE REVIEW

**Comment by PavelLaptev** [comment]
I'm actually thinking we can make this as a default behavior and remove this setting.

**Comment by PavelLaptev** [comment]
Another thing I need to do is return lanes scrollbars

**Comment by mtsgrd** [comment]
@PavelLaptev this is perhaps not the right PR, but I noticed that grabbing the scrollbar and scrolling is glitchy. Let me know if this is something you want me to look into?

https://github.com/gitbutlerapp/gitbutler/assets/1300356/fb0b7a20-2298-4c07-a216-db1093df0e27

**Comment by PavelLaptev** [comment]
@mtsgrd yes. Can you check it out please?

Can't reproduce it on my machine, so not sure what could it be.

https://github.com/gitbutlerapp/gitbutler/assets/18498712/d818eda5-c0c0-457b-ab71-536d9e5f5f4f

**Pull request merged**
