### PR TITLE
Boosting my contribution score

### PR DESCRIPTION
**Pull request by Caleb-T-Owens**

### CODE REVIEW

**Review by krlvi — APPROVED** [review]
Nice! 🎉

**Comment by Byron** [comment]
> [Yes Kiril, I know its an abrv., but its consistent with what Byron started…](https://github.com/gitbutlerapp/gitbutler/pull/4523/commits/f4569ff4da3b23738ccb44e479da9fee5d188c38) 
 
And I didn't even think about it, apologies if this isn't according to what was originally desired. Please feel free to rename to whatever works, even though personally particularly for internal functions (which most of these are), I think short variable names make code easier to read as lines stay shorter.

**Comment by Caleb-T-Owens** [comment]
> > [Yes Kiril, I know its an abrv., but its consistent with what Byron started…](https://github.com/gitbutlerapp/gitbutler/pull/4523/commits/f4569ff4da3b23738ccb44e479da9fee5d188c38)
> 
> And I didn't even think about it, apologies if this isn't according to what was originally desired. Please feel free to rename to whatever works, even though personally particularly for internal functions (which most of these are), I think short variable names make code easier to read as lines stay shorter.

@Byron

Very sorry! It was not meant to be a complaint at your naming at all! I like to avoid abbreviations (IE repository over repo), and Kiril tends to find it humorous to point out whenever I do in fact use an abbreviation. Making a commit like that would have been far too much fuel for him, so I was just getting ahead of the curve there.

**Comment by Byron** [comment]
Makes perfect sense :D! And of course I am glad `ctx` can stay… for now 😅.

**Comment by krlvi** [comment]
> Makes perfect sense :D! And of course I am glad `ctx` can stay… for now 😅.

we are never calling `ctx` `context`... its sooo many letters to read

**Comment by Caleb-T-Owens** [comment]
@krlvi I know you're a slow typer, but it shouldn't be that hard to type `context`...

**Pull request merged**
